name: flutter_capston2025
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0' # Flutter 최신 버전까지 호환되도록 수정

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  shared_preferences: ^2.3.0 # 테마 색상 저장을 위해 추가
  sticky_headers: ^0.3.0+2 # 날짜별 그룹화를 위해 추가
  intl: ^0.19.0 # 날짜 포맷팅을 위해 추가
  cupertino_icons: ^1.0.8
  socket_io_client: ^2.0.3 # 서버 통신을 위한 flutter socket io
  google_fonts: ^5.0.0 #레트로 느낌나는 폰트

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cards/
    - assets/images/
    - assets/images/insect1.png
    - assets/images/insect2.png
    - assets/images/insect3.png
    - assets/images/insect4.png
    - assets/images/insect5.png
    - assets/images/insect6.png
    - assets/images/space_bg.png
    - assets/icons/camera_guide.png


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700