name: flutter_capston2025
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0' # Flutter 최신 버전까지 호환되도록 수정

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.8
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  shared_preferences: ^2.3.0 # 테마 색상 저장을 위해 추가
  sticky_headers: ^0.3.0+2 # 날짜별 그룹화를 위해 추가
  intl: ^0.20.2 # 날짜 포맷팅을 위해 추가
  cupertino_icons: ^1.0.8
  socket_io_client: ^3.1.2 # 서버 통신을 위한 flutter socket io
  google_fonts: ^6.2.1 #레트로 느낌나는 폰트

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^25.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/cards/
    - assets/images/
    - assets/icons/
    - assets/images/camera_page/
    - assets/images/collection_page/
    - assets/images/family_detail_page/
    - assets/images/cards/
    - assets/images/guides/
    - assets/images/BugStrike_user_images.png
    - assets/images/collection_page/insect1.png
    - assets/images/collection_page/insect2.png
    - assets/images/collection_page/insect3.png
    - assets/images/collection_page/insect4.png
    - assets/images/collection_page/insect5.png
    - assets/images/collection_page/insect6.png
    - assets/images/camera_page/space_bg.png
    - assets/images/background/forest_background.png
    - assets/images/family_detail_page/나비/
    - assets/images/family_detail_page/딱정벌레/
    - assets/images/family_detail_page/벌/
    - assets/images/family_detail_page/나비/호랑나비과/
    - assets/images/family_detail_page/나비/흰나비과/
    - assets/images/family_detail_page/딱정벌레/사슴벌레과/
    - assets/images/family_detail_page/딱정벌레/풍뎅이과/
    - assets/images/family_detail_page/벌/꿀벌과/
    - assets/images/family_detail_page/벌/말벌과/
    - assets/images/family_detail_page/나비/호랑나비과/호랑나비1.jpg
    - assets/images/family_detail_page/나비/흰나비과/흰나비1.jpg
    - assets/images/family_detail_page/딱정벌레/사슴벌레과/사슴벌레1.jpg
    - assets/images/family_detail_page/딱정벌레/풍뎅이과/풍뎅이1.jpg
    - assets/images/family_detail_page/벌/꿀벌과/꿀벌1.jpg
    - assets/images/family_detail_page/벌/말벌과/말벌1.jpg
    - assets/icons/camera_guide.png
    - assets/icons/rock.png
    - assets/icons/scissors.png
    - assets/icons/paper.png
    - assets/images/guides/guide1.png
    - assets/images/guides/guide2.png


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700